# Generated by Django 5.2.1 on 2025-09-11 17:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['item_number'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='dynamics_se_search__0b2dfa_gin'), models.Index(fields=['item_number'], name='dynamics_se_item_nu_59132c_idx'), models.Index(fields=['last_updated'], name='dynamics_se_last_up_26e69c_idx')],
            },
        ),
    ]
