# Generated by Django 5.2.1 on 2025-09-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='part',
            name='dynamics_se_search__0b2dfa_gin',
        ),
    ]
