# Generated by Django 5.2.1 on 2025-09-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics_search', '0002_remove_part_dynamics_se_search__0b2dfa_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='product_group_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='part',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='unit_cost_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='part',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='vendor_product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='part',
            name='vendor_product_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
