# Generated by Django 5.2.1 on 2025-09-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics_search', '0003_part_product_group_id_part_unit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_session', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dynamics_se_created_433bd5_idx'), models.Index(fields=['user_session'], name='dynamics_se_user_se_60c312_idx')],
            },
        ),
    ]
