# Generated by Django 5.2.6 on 2025-09-04 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D365Heater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=64)),
                ('dash_number', models.CharField(blank=True, max_length=32, null=True)),
                ('heater_diameter', models.IntegerField()),
                ('heater_height', models.FloatField()),
                ('stack_diameter', models.IntegerField()),
                ('flange_inlet', models.FloatField()),
                ('heater_model', models.CharField(max_length=32)),
                ('material', models.CharField(max_length=32)),
                ('gas_train_size', models.FloatField()),
                ('gas_train_mount', models.CharField(max_length=8)),
                ('btu', models.FloatField()),
                ('hand', models.CharField(max_length=16)),
                ('heater_ab', models.CharField(max_length=8)),
                ('heater_single_dual', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='D365Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=64, unique=True)),
                ('job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='D365Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=64)),
                ('dash_number', models.CharField(blank=True, max_length=32, null=True)),
                ('pump_type', models.CharField(max_length=16)),
                ('pump_pressure', models.CharField(max_length=8)),
                ('system_type', models.CharField(max_length=8)),
                ('hp', models.FloatField()),
                ('material', models.CharField(max_length=32)),
                ('skid_length', models.FloatField()),
                ('skid_width', models.FloatField()),
                ('skid_height', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='D365StackEconomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=64)),
                ('dash_number', models.CharField(blank=True, max_length=32, null=True)),
                ('diameter', models.IntegerField()),
                ('height', models.IntegerField()),
                ('material', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='D365Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=64)),
                ('dash_number', models.CharField(blank=True, max_length=32, null=True)),
                ('tank_diameter', models.IntegerField()),
                ('tank_height', models.IntegerField()),
                ('tank_inches', models.FloatField()),
                ('material', models.CharField(max_length=32)),
                ('tank_type', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
