# Generated by Django 5.2.6 on 2025-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d365', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTURating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_mmbtu', models.FloatField(unique=True)),
            ],
            options={
                'ordering': ['value_mmbtu'],
            },
        ),
        migrations.CreateModel(
            name='FlangeInlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_inch', models.FloatField(unique=True)),
            ],
            options={
                'ordering': ['size_inch'],
            },
        ),
        migrations.CreateModel(
            name='GasTrainMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('display_name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GasTrainSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_inch', models.FloatField(unique=True)),
            ],
            options={
                'ordering': ['size_inch'],
            },
        ),
        migrations.CreateModel(
            name='HeaterDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_inch', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['diameter_inch'],
            },
        ),
        migrations.CreateModel(
            name='HeaterHandRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('display_name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HeaterHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_ft', models.FloatField(unique=True)),
            ],
            options={
                'ordering': ['height_ft'],
            },
        ),
        migrations.CreateModel(
            name='HeaterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HeaterModelRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Horsepower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.FloatField(unique=True)),
            ],
            options={
                'ordering': ['hp'],
            },
        ),
        migrations.CreateModel(
            name='PumpMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PumpPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('display_name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PumpTypeRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('display_name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StackDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_inch', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['diameter_inch'],
            },
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('display_name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TankDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_inch', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['diameter_inch'],
            },
        ),
        migrations.CreateModel(
            name='TankHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_ft', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['height_ft'],
            },
        ),
        migrations.CreateModel(
            name='TankHeightInches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_ft', models.IntegerField(unique=True)),
                ('inches', models.FloatField()),
            ],
            options={
                'ordering': ['height_ft'],
            },
        ),
        migrations.CreateModel(
            name='TankMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TankType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('display_name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
