# Generated by Django 5.2.6 on 2025-09-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d365', '0002_bturating_flangeinlet_gastrainmount_gastrainsize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaterABRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('display_name', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StackHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_ft', models.FloatField(unique=True)),
            ],
            options={
                'ordering': ['height_ft'],
            },
        ),
    ]
