# Generated by Django 5.2.1 on 2025-09-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d365', '0003_heaterabref_stackheight'),
    ]

    operations = [
        migrations.AddField(
            model_name='d365heater',
            name='stack_height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
