# Generated by Django 5.2.1 on 2025-09-09 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d365', '0004_d365heater_stack_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='D365GeneratedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=64)),
                ('section', models.CharField(max_length=16)),
                ('item_number', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('bom', models.CharField(max_length=64)),
                ('template', models.CharField(max_length=64)),
                ('product_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['job_number', 'section', 'item_number'],
                'unique_together': {('job_number', 'section', 'item_number')},
            },
        ),
    ]
